import { Document, Packer, Paragraph, Table, TableCell, TableRow, TextRun } from "docx";
import ExcelJS from "exceljs";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

interface ExportInput {
  title: string;
  subtitle?: string;
  rows: Array<Record<string, unknown>>;
  preparedBy?: string;
}

export async function buildProfessionalPdf(input: ExportInput) {
  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  let page = pdf.addPage([595, 842]);
  let y = 792;

  page.drawRectangle({ x: 0, y: 760, width: 595, height: 82, color: rgb(0.04, 0.08, 0.14) });
  page.drawText("ContractorOps", { x: 40, y: 805, size: 18, font: bold, color: rgb(1, 0.78, 0.18) });
  page.drawText(input.title, { x: 40, y: 775, size: 22, font: bold, color: rgb(1, 1, 1) });
  if (input.subtitle) page.drawText(input.subtitle, { x: 40, y: 742, size: 10, font, color: rgb(0.25, 0.28, 0.34) });

  y = 710;
  page.drawText(`Prepared by: ${input.preparedBy || "ContractorOps"}`, { x: 40, y, size: 10, font, color: rgb(0.25, 0.28, 0.34) });
  y -= 28;

  const columns = Object.keys(input.rows[0] || { message: "No data" }).slice(0, 6);
  page.drawRectangle({ x: 40, y: y - 12, width: 515, height: 24, color: rgb(0.93, 0.95, 0.98) });
  columns.forEach((column, index) => {
    page.drawText(column, { x: 48 + index * 84, y: y - 4, size: 8, font: bold, color: rgb(0.1, 0.12, 0.18) });
  });
  y -= 30;

  for (const row of input.rows.length ? input.rows : [{ message: "No records found for the selected filters." }]) {
    if (y < 90) {
      page.drawText("Signature", { x: 40, y: 45, size: 10, font, color: rgb(0.35, 0.35, 0.35) });
      page = pdf.addPage([595, 842]);
      y = 790;
    }
    columns.forEach((column, index) => {
      const value = String(row[column] ?? "").slice(0, 22);
      page.drawText(value, { x: 48 + index * 84, y, size: 8, font, color: rgb(0.18, 0.2, 0.25) });
    });
    y -= 20;
  }

  page.drawLine({ start: { x: 40, y: 70 }, end: { x: 190, y: 70 }, thickness: 1, color: rgb(0.65, 0.65, 0.65) });
  page.drawText("Authorized signature", { x: 40, y: 52, size: 9, font, color: rgb(0.35, 0.35, 0.35) });
  page.drawText("Generated by ContractorOps", { x: 395, y: 32, size: 8, font, color: rgb(0.45, 0.45, 0.45) });

  return Buffer.from(await pdf.save());
}

export async function buildExcel(input: ExportInput) {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "ContractorOps";
  workbook.created = new Date();
  const worksheet = workbook.addWorksheet("Report", {
    views: [{ state: "frozen", ySplit: 1 }]
  });
  const rows = input.rows.length ? input.rows : [{ message: "No records found" }];
  const columns = Object.keys(rows[0]);
  worksheet.columns = columns.map((column) => ({ header: column, key: column, width: 24 }));
  rows.forEach((row) => worksheet.addRow(row));
  worksheet.getRow(1).font = { bold: true, color: { argb: "FFFFFFFF" } };
  worksheet.getRow(1).fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF0F172A" } };
  worksheet.eachRow((row) => {
    row.eachCell((cell) => {
      cell.border = {
        top: { style: "thin", color: { argb: "FFE2E8F0" } },
        left: { style: "thin", color: { argb: "FFE2E8F0" } },
        bottom: { style: "thin", color: { argb: "FFE2E8F0" } },
        right: { style: "thin", color: { argb: "FFE2E8F0" } }
      };
    });
  });
  return Buffer.from(await workbook.xlsx.writeBuffer());
}

export async function buildWord(input: ExportInput) {
  const columns = Object.keys(input.rows[0] || { message: "No data" });
  const tableRows = [
    new TableRow({
      children: columns.map((column) => new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: column, bold: true })] })] }))
    }),
    ...(input.rows.length ? input.rows : [{ message: "No records found" }]).map(
      (row) =>
        new TableRow({
          children: columns.map((column) => new TableCell({ children: [new Paragraph(String(row[column] ?? ""))] }))
        })
    )
  ];

  const doc = new Document({
    sections: [
      {
        children: [
          new Paragraph({ children: [new TextRun({ text: "ContractorOps", bold: true, size: 28 })] }),
          new Paragraph({ children: [new TextRun({ text: input.title, bold: true, size: 32 })] }),
          new Paragraph(input.subtitle || ""),
          new Paragraph(""),
          new Table({ rows: tableRows }),
          new Paragraph(""),
          new Paragraph("Authorized signature: ______________________")
        ]
      }
    ]
  });

  return Buffer.from(await Packer.toBuffer(doc));
}
